apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: apps
        image: artifacts.tekuro.io/apps:45eb0729db09d4501390096b621001e3a47d0457
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
