apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: apps
        image: artifacts.tekuro.io/apps:11cc21fd7d5713d04320c85b9aae337b3314b406
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: regcred
