apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx 
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
      - name: apps
        image: artifacts.tekuro.io/apps:latest
        ports:
        - containerPort: 8080
