name: CD

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  IMAGE_NAME: artifacts.tekuro.io/apps

jobs:
  build-and-deploy:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Tekuro Artifacts
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Update values.yaml
        run: |
          cd deployment
          sed -i 's/image: ${{ env.IMAGE_NAME }}:.*/image: ${{ env.IMAGE_NAME }}:${{ github.sha }}' deployment.yaml
          git config --global user.name 'Github Actions'
          git config --global user.email 'actions@github.com'
          git add deployment.yaml
          git commit -m "Update deployment.yaml"
          git push
